version = 1

[merge]
automerge_label = "ğŸš€ Status: ship it"
blocking_title_regex = "^WIP.*"
blocking_labels = ["ğŸ– Status: On Hold", "ğŸš§ Status: WIP"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = true
notify_on_conflict = true
optimistic_updates = true
