sudo: false
language: node_js
node_js:
  - '10'

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

script:
  # the jest.bundle.config.js tests run on the bundle,
  # so we need to build it first
  - yarn build
  - yarn run jest --projects jest.*.config.js --maxWorkers=4 --reporters jest-silent-reporter
  - yarn snapshot
  - "! test -f fail-tests-because-there-was-an-unhandled-rejection.lock"

before_deploy: yarn build

deploy:
  provider: npm
  email: npmjs@commercetools.com
  api_key:
    secure: KSowahYa4Q4vtLEIaetRTdAZ9cdHwD4c5mnpK0DFi21L0BNUjBzcaocR5Hr3PV62fzdFDHViZ36I3vWojznCmlq1POODHHrFoNycWk+wpI3NJQ887zNbsDIhpDqwN4HPv0TuxfS1r5WiApE6ynm0g+f7DL42+1FAnIIDyKsTNHlimRWuQVk7psinvNs4AyjEyRbvHCEDyRHBXbphX48J1ZUu/uZ9xNIsiWG/1RH0WH1lcT6VHctpy9ZXvmLKw0UilMkbwrNen5OHLQVxp4SrT/4+rxh/msdGwkiH00hi6C0DZizkXxZ+8SGoi//r3l3qMMdhjahBcIp/CEqYu+g59CXIRU1mTEAGf1el9K2dG/cdt9U9D/pQJzlVKgDNsB8XN70wkpoIgdqy2GsEHvth589hsxOI7HlP4NyO36Cv0kIktJDQOwhNd7UQ11p4D5aK8laHcYSD1SUF5sTYpFb8UB8mruWVGf7/siQQsnv9Q+CVkjJKwxvVJlBDr52jQ84+w3FaCoTeVSwOAxTEuK5x9Q7V2KUSxWVDd4MgNWoQkijFEqfe2QbzCW4qpsI3qXSwNKaMYKclodSD93KaTX8thZPy4MCbBKLdX3z8a/ibCbZa4Z83yo1ASFLbFYDimQFjSlQdeV+sia9A36iZSOvSnHqPhj6vhsaFvzgSA06YIjk=
  skip_cleanup: true
  on:
    tags: true
  tag: next

# Keep it disabled until this issue is clarified
# https://twitter.com/emmenko/status/1040544486101856256
# after_deploy: yarn docs:publish
